# loop logistics
epochs: 30
iterations: 2000
start_epoch: 0
print_freq: 50

# loss
contrast_type: "class_aware"
ce_type: "standard" # ["standard", "symmetric", "smoothed", "soft"]
lambda_cls: 1.0
lambda_ins: 1.0
lambda_div: 1.0

# algo-related stuff
aug_versions: "wss" # ["w", "ws", "wss", "ss", "wssn"]
dist_type: "cosine" # ["cosine", "euclidean"]
ce_sup_type: "weak_strong" # ["weak_all", "weak_weak", "weak_strong", "self_all"]
refine_method: "nearest_neighbors"
num_neighbors: 3
queue_size: -1
epoch_labeling: false

# ours
patch_height: 28
mix_prob: 0.8